# Generated by Django 5.2.6 on 2025-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KentselDonusumBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=255)),
                ('ada_no', models.CharField(blank=True, max_length=50, null=True)),
                ('parsel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bina_yasi', models.PositiveIntegerField()),
                ('daire_sayisi', models.PositiveIntegerField()),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
